name: "Sync Plugin Versions"
description: "Checks or updates version numbers in plugin files to match the latest Git tag."
inputs:
  fix:
    type: boolean
    description: "Set to true to update files, false to only check"
    required: false
    default: false
  plugin_main_file:
    description: "Main plugin file (e.g., wphaven.php)"
    required: true
  readme_file:
    description: "Readme file (e.g., readme.txt)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Ensure git is available
      run: git --version

    - name: Make script executable
      run: chmod +x "${{ github.action_path }}/sync-versions.sh"

    - name: Skip on branch (only run on tags)
      shell: bash
      run: |
        if [[ "${GITHUB_REF:-}" != refs/tags/* ]]; then
          echo "Not running on a tag. Skipping sync-versions."
          exit 0
        fi

    - name: Sync or check versions
      shell: bash
      run: |
        "${{ github.action_path }}/sync-versions.sh" "${{ inputs.plugin_main_file }}" "${{ inputs.readme_file }}" "${{ inputs.fix }}"
