name: "Sync Plugin Versions"
description: |
  Checks or updates version numbers in plugin files to match the latest Git tag.
  
  - On a tag (release) run, this action compares the version in your main plugin file and readme.txt to the latest local Git tag.
  - If `fix` is `false` (default), the action will fail if the versions do not match the tag.
  - If `fix` is `true`, the action will update the version numbers in both files to match the tag.
  - If run on a branch (not a tag), the action will detect this and exit successfully without making changes or failing.
  
  This ensures your plugin version numbers are always in sync with your release tags, and prevents accidental mismatches.
inputs:
  fix:
    type: boolean
    description: "Set to true to update files, false to only check"
    required: false
    default: false
  plugin_main_file:
    description: "Main plugin file (e.g., wphaven.php)"
    required: true
  readme_file:
    description: "Readme file (e.g., readme.txt)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Ensure git is available
      run: git --version

    - name: Make script executable
      run: chmod +x "${{ github.action_path }}/sync-versions.sh"

    - name: Skip on branch (only run on tags)
      shell: bash
      run: |
        if [[ "${GITHUB_REF:-}" != refs/tags/* ]]; then
          echo "Not running on a tag. Skipping sync-versions."
          exit 0
        fi

    - name: Sync or check versions
      shell: bash
      run: |
        "${{ github.action_path }}/sync-versions.sh" "${{ inputs.plugin_main_file }}" "${{ inputs.readme_file }}" "${{ inputs.fix }}"
