name: WordPress Plugin Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]"
  workflow_dispatch:

jobs:
  call-shared-wordpress-plugin-release:
    uses: embold/.github/.github/workflows/wordpress-plugin-release.yml@main
    with:
      tag: ${{ github.ref_name }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
