name: 'Docker Build and Push'
description: 'Reusable composite action to build and push Docker images with Buildx.'
inputs:
  context:
    description: 'Build context path'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  tags:
    description: 'Docker image tags (newline separated)'
    required: true
  build-args:
    description: 'Build arguments (newline separated)'
    required: false
    default: ''
  username:
    description: 'Docker Hub username'
    required: true
  password:
    description: 'Docker Hub password or token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ inputs.tags }}
        build-args: ${{ inputs.build-args }}
