name: Release Ruby Gem

on:
  workflow_call:
    inputs:
      gem_name:
        description: "Name of the Ruby gem"
        type: string
        required: false
        default: ${{ github.repository }}
      gemspec:
        description: "Path to the gemspec file"
        type: string
        required: false
        default: ${{ github.repository }}.gemspec

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - name: Build gem
        run: |
          gem build ${{ inputs.gemspec }}
      - name: Publish to GitHub Packages
        env:
          GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem push --key github --host https://rubygems.pkg.github.com/emboldagency ${{ inputs.gem_name }}-*.gem
      - name: Upload gem to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ inputs.gem_name }}-*.gem
          asset_name: ${{ inputs.gem_name }}.gem
          asset_content_type: application/gem
